# Generated by Django 5.0.7 on 2024-07-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_idoso_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoso_dados',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Pre_Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pas_1', models.CharField(max_length=7)),
                ('pad_1', models.CharField(max_length=7)),
                ('pas_2', models.CharField(max_length=7)),
                ('pad_2', models.CharField(max_length=7)),
                ('pas_3', models.CharField(max_length=7)),
                ('pad_3', models.CharField(max_length=7)),
                ('frequencia_card', models.PositiveSmallIntegerField()),
                ('saturacao_oxg', models.PositiveSmallIntegerField()),
                ('qualidade_sono', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], max_length=10)),
                ('bem_estar', models.CharField(choices=[('Muito ruim', 'Muito ruim'), ('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], max_length=10)),
                ('pain', models.CharField(choices=[('Sem dor', 'Sem dor'), ('Dor leve', 'Dor leve'), ('Dor moderada', 'Dor moderada'), ('Dor intensa', 'Dor intensa'), ('Pior dor possível', 'Pior dor possível')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idoso_dados', to_field='cpf')),
            ],
        ),
    ]
