# Generated by Django 5.0.7 on 2024-07-14 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_idoso_dados_cpf_pre_intervencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos_Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('pas_1', models.CharField(max_length=7)),
                ('pad_1', models.CharField(max_length=7)),
                ('pas_2', models.CharField(max_length=7)),
                ('pad_2', models.CharField(max_length=7)),
                ('pas_3', models.CharField(max_length=7)),
                ('pad_3', models.CharField(max_length=7)),
                ('frequencia_card', models.PositiveSmallIntegerField()),
                ('saturacao_oxg', models.PositiveSmallIntegerField()),
                ('tempo_cam', models.DurationField()),
                ('esforco', models.CharField(choices=[('Muito leve', 'Muito leve'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Muito intenso', 'Muito intenso')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idoso_dados', to_field='cpf')),
            ],
        ),
    ]
