# Generated by Django 5.0.7 on 2024-07-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pos_intervencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_intervencao',
            name='esforco',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
