# Generated by Django 5.0.4 on 2024-07-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pos_intervencao_esforco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pre_Intervencao',
            new_name='Atendimento',
        ),
        migrations.DeleteModel(
            name='Pos_Intervencao',
        ),
    ]
