# Generated by Django 5.0.4 on 2024-07-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_pre_intervencao_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='user',
            new_name='cpf_idoso',
        ),
    ]
