# Generated by Django 5.0.7 on 2024-07-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_atendimento_cpf_idoso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('treino_pres', models.CharField(max_length=20)),
                ('tempo_pres', models.PositiveSmallIntegerField()),
                ('distancia_pres', models.PositiveSmallIntegerField()),
                ('tempo_exec', models.DurationField()),
                ('distancia_exec', models.FloatField()),
                ('cpf_idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idoso_dados', to_field='cpf')),
            ],
        ),
    ]
