# Generated by Django 5.0.7 on 2024-07-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='tempo_exec',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
