# Generated by Django 5.0.7 on 2024-07-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_treino_tempo_exec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('per_cintura', models.FloatField()),
                ('per_quadril', models.FloatField()),
                ('per_panturrilha', models.FloatField()),
                ('marcha6', models.FloatField()),
                ('hg_direita1', models.FloatField()),
                ('hg_esquerda1', models.FloatField()),
                ('hg_direita2', models.FloatField()),
                ('hg_esquerda2', models.FloatField()),
                ('ir_vir1', models.FloatField()),
                ('ir_vir2', models.FloatField()),
                ('cpf_idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idoso_dados', to_field='cpf')),
            ],
        ),
    ]
