# Generated by Django 5.0.4 on 2024-07-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_treino_tempo_exec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('cpf_idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idoso_dados', to_field='cpf')),
            ],
        ),
    ]
