# Generated by Django 5.0.4 on 2024-07-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_avaliacao'),
        ('api', '0010_exame'),
    ]

    operations = [
    ]
